# This Dockerfile runs 'stack build', thus creating an image
# containing a warm ~/.stack directory.
# This is used to speed up the building of the actual image
# we want to use for the tests.

FROM fpco/stack-build:lts-14.27
RUN mkdir /opt/build
RUN mkdir /opt/build/bin
COPY . /opt/build
RUN cd /opt/build && stack build --system-ghc
