ThisBuild / libraryDependencySchemes ++= Seq(
  "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always
)
addSbtPlugin("com.eed3si9n"              % "sbt-projectmatrix"        % "0.9.0")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"                  % "0.4.3")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release"           % "1.5.11")
addSbtPlugin("com.47deg"                 % "sbt-microsites"           % "1.3.4")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"             % "2.5.0")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"                 % "2.3.6")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"               % "5.9.0")
addSbtPlugin("com.alejandrohdezma"       % "sbt-github"               % "0.11.6")
addSbtPlugin("com.alejandrohdezma"       % "sbt-github-header"        % "0.11.6")
addSbtPlugin("com.alejandrohdezma"       % "sbt-github-mdoc"          % "0.11.6")
addSbtPlugin("com.alejandrohdezma"       % "sbt-remove-test-from-pom" % "0.1.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"             % "0.3.1")
addSbtPlugin("ch.epfl.scala"             % "sbt-missinglink"          % "0.3.3")
addSbtPlugin("io.higherkindness"         % "sbt-mu-srcgen"            % "0.29.1")
